SET SESSION FOREIGN_KEY_CHECKS=0;


/* Create Tables */

CREATE TABLE MEMBER_FOLLOWING
(
	MEMBER_FOLLOWING_ID BIGINT NOT NULL UNIQUE AUTO_INCREMENT COMMENT '会員フォローイングID',
	MY_MEMBER_ID INT NOT NULL COMMENT '自分',
	YOUR_MEMBER_ID INT NOT NULL COMMENT '相手',
	FOLLOW_DATETIME DATETIME NOT NULL COMMENT 'FOLLOW_DATETIME',
	PRIMARY KEY (MEMBER_FOLLOWING_ID),
	CONSTRAINT MY_FOLLOW_YOU UNIQUE (MY_MEMBER_ID, YOUR_MEMBER_ID)
) COMMENT = '会員フォローイング';


CREATE TABLE MEMBER
(
	MEMBER_ID INT NOT NULL UNIQUE AUTO_INCREMENT COMMENT '会員ID',
	MEMBER_NAME VARCHAR(50) NOT NULL COMMENT '会員名称',
	MEMBER_ACCOUNT VARCHAR(20) NOT NULL UNIQUE COMMENT '会員アカウント',
	MEMBER_STATUS_CODE CHAR(3) NOT NULL COMMENT '会員ステータスコード',
	PRIMARY KEY (MEMBER_ID)
) COMMENT = '会員';


CREATE TABLE TWEET
(
	TWEET_ID BIGINT NOT NULL UNIQUE AUTO_INCREMENT COMMENT 'ツイートID',
	MEMBER_ID INT NOT NULL COMMENT '会員ID',
	TWEET_MESSAGE VARCHAR(140) NOT NULL COMMENT 'ツイート内容',
	TWEET_DATETIE DATETIME NOT NULL COMMENT 'ツイート日時',
	PRIMARY KEY (TWEET_ID)
) COMMENT = 'ツイート';


CREATE TABLE MEMBER_STATUS
(
	MEMBER_STATUS_CODE CHAR(3) NOT NULL COMMENT '会員ステータスコード',
	MEMBER_STATUS_NAME VARCHAR(20) NOT NULL COMMENT '会員ステータス名称',
	DISPLAY_ORDER INT NOT NULL UNIQUE COMMENT '表示順',
	PRIMARY KEY (MEMBER_STATUS_CODE)
) COMMENT = '会員ステータス';


CREATE TABLE MEMBER_SECURITY
(
	MEMBER_ID INT NOT NULL UNIQUE COMMENT '会員ID',
	PASSWORD VARCHAR(100) NOT NULL COMMENT 'パスワード',
	PRIMARY KEY (MEMBER_ID)
) COMMENT = '会員セキュリティ';



/* Create Foreign Keys */

ALTER TABLE MEMBER_FOLLOWING
	ADD FOREIGN KEY (MY_MEMBER_ID)
	REFERENCES MEMBER (MEMBER_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE MEMBER_FOLLOWING
	ADD FOREIGN KEY (YOUR_MEMBER_ID)
	REFERENCES MEMBER (MEMBER_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE TWEET
	ADD FOREIGN KEY (MEMBER_ID)
	REFERENCES MEMBER (MEMBER_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE MEMBER_SECURITY
	ADD FOREIGN KEY (MEMBER_ID)
	REFERENCES MEMBER (MEMBER_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE MEMBER
	ADD FOREIGN KEY (MEMBER_STATUS_CODE)
	REFERENCES MEMBER_STATUS (MEMBER_STATUS_CODE)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;



/* Create Indexes */

CREATE INDEX IX_MY_MEMBER_ID_YOUR_MEMBER_ID ON MEMBER_FOLLOWING (MY_MEMBER_ID ASC, YOUR_MEMBER_ID ASC);
CREATE INDEX IX_MEMBER_NAME ON MEMBER (MEMBER_NAME ASC);
CREATE INDEX IX_TWEET_DATETIME ON TWEET (TWEET_DATETIE ASC);



